lot:
  jwt:
    secret-key: lotbackend
    ttl: 7200000
    token-name: Authorization
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-15-34-237.us-east-2.compute.amazonaws.com:5432/mydb
    username: myuser
    password: slb123456
    driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true