lot:
  jwt:
    secret-key: lotbackend
    ttl: 7200000
    token-name: Authorization
spring:
  datasource:
    url: jdbc:postgresql://ec2-18-226-165-233.us-east-2.compute.amazonaws.com:5432/mydb?currentSchema=public
