lot:
  jwt:
    secret-key: LoTBackEndSecurityKeyUsedForAuthorization
    ttl: 7200000
    token-name: Authorization
spring:
  datasource:
    url: jdbc:postgresql://172.191.111.81:5432/slb_db2
    username: myuser
    password: slb123456
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true