package com.lot.server.category.domain.entity;

public class CategoryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.product_id
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.product_name
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.number_part_check_out
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    private Integer numberPartCheckOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.number_part_in_stock
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    private Integer numberPartInStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.total_cost
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    private Double totalCost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.product_id
     *
     * @return the value of public.product.product_id
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.product_id
     *
     * @param productId the value for public.product.product_id
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.product_name
     *
     * @return the value of public.product.product_name
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.product_name
     *
     * @param productName the value for public.product.product_name
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.number_part_check_out
     *
     * @return the value of public.product.number_part_check_out
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public Integer getNumberPartCheckOut() {
        return numberPartCheckOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.number_part_check_out
     *
     * @param numberPartCheckOut the value for public.product.number_part_check_out
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public void setNumberPartCheckOut(Integer numberPartCheckOut) {
        this.numberPartCheckOut = numberPartCheckOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.number_part_in_stock
     *
     * @return the value of public.product.number_part_in_stock
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public Integer getNumberPartInStock() {
        return numberPartInStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.number_part_in_stock
     *
     * @param numberPartInStock the value for public.product.number_part_in_stock
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public void setNumberPartInStock(Integer numberPartInStock) {
        this.numberPartInStock = numberPartInStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.total_cost
     *
     * @return the value of public.product.total_cost
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public Double getTotalCost() {
        return totalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.total_cost
     *
     * @param totalCost the value for public.product.total_cost
     *
     * @mbg.generated Mon Mar 24 22:32:19 CDT 2025
     */
    public void setTotalCost(Double totalCost) {
        this.totalCost = totalCost;
    }
}