package com.lot.server.component.domain.entity;

public class ComponentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.part.part_id
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    private Integer partId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.part.status
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.part.product_name
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.part.product_id
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.part.cost
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.part.part_name
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    private String partName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.part.part_id
     *
     * @return the value of public.part.part_id
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public Integer getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.part.part_id
     *
     * @param partId the value for public.part.part_id
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public void setPartId(Integer partId) {
        this.partId = partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.part.status
     *
     * @return the value of public.part.status
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.part.status
     *
     * @param status the value for public.part.status
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.part.product_name
     *
     * @return the value of public.part.product_name
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.part.product_name
     *
     * @param productName the value for public.part.product_name
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.part.product_id
     *
     * @return the value of public.part.product_id
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.part.product_id
     *
     * @param productId the value for public.part.product_id
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.part.cost
     *
     * @return the value of public.part.cost
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.part.cost
     *
     * @param cost the value for public.part.cost
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.part.part_name
     *
     * @return the value of public.part.part_name
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public String getPartName() {
        return partName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.part.part_name
     *
     * @param partName the value for public.part.part_name
     *
     * @mbg.generated Tue Mar 25 18:29:27 CDT 2025
     */
    public void setPartName(String partName) {
        this.partName = partName;
    }
}